#!/usr/bin/env python3
"""
iconbake - Download and convert SVG icons to 16x16 1bpp C arrays for MyOS.

Usage: python3 iconbake.py <icon_name> <svg_url> [output.h]
"""

import sys
import os
import requests
import cairosvg
from PIL import Image
from io import BytesIO

# Icon definitions: (name, description, svg_url)
ICONS = {
    "terminal": (
        "Terminal",
        "https://raw.githubusercontent.com/feathericons/feather/master/icons/terminal.svg"
    ),
    "folder": (
        "Files",
        "https://raw.githubusercontent.com/feathericons/feather/master/icons/folder.svg"
    ),
    "monitor": (
        "System Monitor",
        "https://raw.githubusercontent.com/feathericons/feather/master/icons/monitor.svg"
    ),
    "help": (
        "Help",
        "https://raw.githubusercontent.com/feathericons/feather/master/icons/help-circle.svg"
    ),
    "about": (
        "About",
        "https://raw.githubusercontent.com/feathericons/feather/master/icons/info.svg"
    ),
    "settings": (
        "Settings",
        "https://raw.githubusercontent.com/feathericons/feather/master/icons/settings.svg"
    ),
    "browser": (
        "Browser",
        "https://raw.githubusercontent.com/feathericons/feather/master/icons/globe.svg"
    ),
    "editor": (
        "Editor",
        "https://raw.githubusercontent.com/feathericons/feather/master/icons/edit.svg"
    ),
    "calculator": (
        "Calculator",
        "https://raw.githubusercontent.com/feathericons/feather/master/icons/calculator.svg"
    ),
    "music": (
        "Music",
        "https://raw.githubusercontent.com/feathericons/feather/master/icons/music.svg"
    ),
}


def download_svg(url):
    """Download SVG from URL."""
    response = requests.get(url, timeout=10)
    response.raise_for_status()
    return response.content


def svg_to_png(svg_data, size=16):
    """Convert SVG to PNG at specified size."""
    png_data = cairosvg.svg2png(
        bytestring=svg_data,
        output_width=size,
        output_height=size,
        background_color="transparent"
    )
    return Image.open(BytesIO(png_data)).convert("RGBA")


def png_to_1bpp(img, threshold=128):
    """Convert RGBA PIL image to 1bpp bitmap (16x16, 2 bytes per row)."""
    # Convert to grayscale with alpha blending on white
    gray = Image.new("L", img.size, 255)
    gray.paste(img, mask=img.split()[3])  # Use alpha as mask

    # Threshold to 1bpp
    bw = gray.point(lambda x: 255 if x > threshold else 0, mode="1")

    # Pack into 1bpp format: 16 rows, 2 bytes per row (16 bits)
    # Bit 0 = leftmost pixel (LSB first within each byte)
    result = bytearray(32)
    pixels = bw.load()
    for y in range(16):
        row_bits = 0
        for x in range(16):
            if pixels[x, y] == 0:  # Black = 1 in 1bpp
                row_bits |= (1 << x)
        result[y * 2] = row_bits & 0xFF
        result[y * 2 + 1] = (row_bits >> 8) & 0xFF

    return result


def format_c_array(name, data):
    """Format bytearray as C array."""
    lines = [f"static const uint8_t icon_{name}[32] = {{"]
    for i in range(0, 32, 8):
        chunk = data[i:i+8]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")
    lines.append("};")
    return "\n".join(lines)


def preview_icon(data):
    """Print ASCII preview of the icon."""
    print("Preview:")
    for y in range(16):
        row_bits = data[y * 2] | (data[y * 2 + 1] << 8)
        line = ""
        for x in range(16):
            line += "█" if (row_bits & (1 << x)) else " "
        print(f"  {line}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 iconbake.py <icon_key|all> [output.h]")
        print("\nAvailable icons:")
        for key, (name, url) in ICONS.items():
            print(f"  {key:12} - {name}")
        print("\n  all          - Generate all icons")
        return 1

    key = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None

    if key == "all":
        icons_to_gen = ICONS.items()
    elif key in ICONS:
        icons_to_gen = [(key, ICONS[key])]
    else:
        print(f"Unknown icon: {key}")
        return 1

    all_output = []
    for icon_key, (name, url) in icons_to_gen:
        print(f"\nProcessing {icon_key} ({name})...")
        try:
            svg_data = download_svg(url)
            png = svg_to_png(svg_data, 16)
            bitmap = png_to_1bpp(png)
            preview_icon(bitmap)
            c_array = format_c_array(icon_key, bitmap)
            all_output.append(c_array)
            print(f"  ✓ Generated {icon_key}")
        except Exception as e:
            print(f"  ✗ Failed: {e}")

    output = "\n\n".join(all_output)

    if output_file:
        with open(output_file, "w") as f:
            f.write("/* Generated by tools/iconbake/iconbake.py */\n")
            f.write("#ifndef ICONS_GENERATED_H\n")
            f.write("#define ICONS_GENERATED_H\n\n")
            f.write("#include <stdint.h>\n\n")
            f.write(output)
            f.write("\n\n#endif\n")
        print(f"\nWritten to {output_file}")
    else:
        print("\n" + "=" * 50)
        print(output)


if __name__ == "__main__":
    main()